os: linux
dist: bionic
language: python
python:
  - "3.7"

cache:
  pip: true

git:
  submodules: false

env:
  global:
    - MAKEFLAGS="-j2"

jobs:
  include:
    - stage: "Tests"
      name: "Python PEP8 checks"
      install:
        - pip install -r conf/requirements.txt
      script:
        - "make format"
        - "test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }"

    - name: "Generate report.hml"
      install:
        - source ./.github/travis/install.sh
      script:
        - "make generate-tests"
        - "make tests USE_ALL_RUNNERS=1 -j2"
        - "make report USE_ALL_RUNNERS=1"
        - "touch out/report/.nojekyll"
      deploy:
        provider: pages
        github_token: $GH_TOKEN
        skip_cleanup: true
        keep_history: true
        local_dir: out/report
        verbose: true
        on:
          branch: master
