os: linux
dist: bionic
language: python
python:
  - "3.7"

cache:
  pip: true
  ccache: true

env:
  global:
    - MAKEFLAGS="-j2"


jobs:
  include:
    - stage: "Tests"
      name: "Python PEP8 checks"
      install:
        - pip install -r conf/requirements.txt
      script:
        - "flake8 $(file generators/* tools/* | sed -ne 's/:.*python.*//pI')"

    - name: "Generate report.hml"
      install:
        - sudo apt-get install gperf -y
        - sudo apt-get install libfl-dev -y
        - sudo apt-get install gcc-8 -y
        - sudo apt-get install g++-8 -y
        - sudo apt-get install yosys -y
        - sudo apt-get install iverilog -y
        - sudo apt-get install verilator -y
        - sudo ln -sf /usr/bin/gcc-8 /usr/bin/gcc
        - sudo ln -sf /usr/bin/g++-8 /usr/bin/g++
        - pip install -r conf/requirements.txt
      script:
        - "make slang"
        - "make odin"
        - "make generate-tests"
        - "make report"
        - "mkdir out/deploy"
        - "cp out/report.html out/deploy/index.html"
        - "touch out/deploy/.nojekyll"
      deploy:
        provider: pages
        github_token: $GH_TOKEN
        skip_cleanup: true
        keep_history: true
        local_dir: out/deploy
        verbose: true
        on:
          branch: master
