name: sv-test-env
channels:
  - symbiflow
  - pkgw-forge
  - conda-forge
dependencies:
#  - symbiflow::iverilog
#  - symbiflow::moore
#  - symbiflow::odin_ii
#  - symbiflow::slang
#  - symbiflow::surelog
#  - symbiflow::sv-parser
#  - symbiflow::tree-sitter-verilog
#  - symbiflow::uhdm-integration-verilator
#  - symbiflow::uhdm-integration-yosys
#  - symbiflow::verible
#  - symbiflow::verilator
#  - symbiflow::yosys
#  - symbiflow::antmicro-yosys
#  - symbiflow::zachjs-sv2v
  - ccache
  - python=3.8
  - pip
  - symbiflow-yosys-plugins
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
