name: build tools
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        tool:
          - icarus
          - moore
          - odin
          - slang
          - surelog
          - sv-parser
          - tree-sitter-verilog
          - verible
          - verilator
          - verilator-uhdm
          - yosys
          - yosys-uhdm
          - zachjs-sv2v

    name: ${{ matrix.tool }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt -qq -y install gperf flex libfl-dev tcl-dev
          pip install -r conf/requirements.txt
      - name: Build
        run: |
          make ${{ matrix.tool }} -j$(nproc)
      - name: Check
        run: |
          make info
